language: node_js
node_js:
  - "stable"
cache: yarn
jobs:
  include:
    - stage: test
      script:
        - echo 'Installing Dependency!'
        - yarn
        - yarn run test
    - stage: deploy
      script:
        - echo 'Deploy!'
        - npm install -g firebase-tools
        - yarn build
        - firebase deploy --token "$FIREBASE_TOKEN"
stages:
  - name: test
    # require the type to be a PR
    if: type = pull_request
  - name: deploy
    # require the type to be push to master
    if: type = pull_request AND branch = main