language: node_js
node_js:
  - "stable"
cache: yarn
script:
  - echo 'Installing Dependency!'
  - yarn
  - yarn run test
  - yarn run build
branches:
  only:
    - main
    - set-up-CI/CD
deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_TOKEN"
  app:
    main: medslink
    set-up-CI/CD: medslink-staging